FROM mysql:8.0.19 
COPY MySQLArticleDatabase/publiceditor-database-dump.sql /docker-entrypoint-initdb.d/

WORKDIR /home/init_database
COPY MySQLArticleDatabase/init_db.sh /home/init_database
COPY MySQLArticleDatabase/mysql.sh /home/init_database
